## NUMPY

#### Numpy does not perform type checking while iterating through objects.

#### Numpy uses fixed types.

#### Numpy uses contiguous memory.

In [2]:
import numpy as np

In [4]:
a = np.arange(5)
print(a)
print(a <= 3)


[0 1 2 3 4]
[ True  True  True  True False]


In [3]:
b = np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]])
print(b)


[[1. 2. 3.]
 [3. 4. 5.]]


In [4]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))


[[100 100 100 100 100]
 [100 100 100 100 100]]


In [6]:
output = np.ones((7, 7))

z = np.zeros((5, 5))
z[3, 3] = 5

output[1:-1, 1:-1] = z

output


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 5., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
b

array([ 1,  2, 20,  4,  5])

In [10]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

b

15