## NUMPY

#### Numpy does not perform type checking while iterating through objects.

#### Numpy uses fixed types.

#### Numpy uses contiguous memory.

In [2]:
import numpy as np

In [4]:
a = np.arange(5)
print(a)
print(a <= 3)


[0 1 2 3 4]
[ True  True  True  True False]


In [3]:
b = np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0]])
print(b)


[[1. 2. 3.]
 [3. 4. 5.]]


In [4]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))


[[100 100 100 100 100]
 [100 100 100 100 100]]


In [6]:
output = np.ones((7, 7))

z = np.zeros((5, 5))
z[3, 3] = 5

output[1:-1, 1:-1] = z

output


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 5., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
b

array([ 1,  2, 20,  4,  5])

In [10]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

b

15

In [3]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [4]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [7]:
a = np.array([0, 1, 0, 1, 0])

b = np.array([1, 0, 1, 0, 1])

a*b


array([0, 0, 0, 0, 0])

In [8]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0